version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    - package
    - pypi:
        requires:
        - package

jobs:
  package:
    docker:
    - image: cimg/python:3.6
    steps:
    - setup_remote_docker
    #TODO Move into dockerfile for image
    - run:
        name: Install Docker client
        command: |
          set -x
          VER="20.10.8-ce"
          curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
    - checkout
    - run: pyenv versions
    - run:
        name: Upgrade pip
        command: pip install -U pip
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pkg-manager: pip
        pip-dependency-file: test_requirements.txt
    - run:
        name: Run tests
        command: |
          pylint buildrunner
          pytest
  pypi:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
          twine upload -u "__token__" dist/*

