version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  build:
    jobs:
    - package
    - pypi:
        requires:
        - package

jobs:
  package:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - run: pyenv versions
    - python/install-packages:
        pkg-manager: pip
    - python/install-packages:
        pkg-manager: pip
        pip-dependency-file: test_requirements.txt
    - run:
        name: Run tests
        command: pytest --pylint
  pypi:
    docker:
    - image: cimg/python:3.6
    steps:
    - checkout
    - python/install-packages:
        pkg-manager: pip
    - run:
        name: Deploy to pypi
        command: |
          pip install -U pip
          python setup.py sdist bdist_wheel
          pip install twine
          twine check dist/*
          twine upload -u "__token__" dist/*

