#!/bin/bash

if [ -z "$DOCKER_HOST" ]; then
    export DOCKER_HOST=unix:///var/run/docker.sock
fi
env_vars="-e HOME=/$HOME"
for var in $(env | egrep -i "^(DOCKER_HOST|DOCKER_TLS_VERIFY|DOCKER_CERT_PATH|BUILDRUNNER_)")
do
	  if [[ "$OS" = Windows* ]]
	  then
		    # Replace =c: with =//c
		    var=$( echo "$var" | sed "s,=\([a-z]\):,=//\L\1,gi" )
    fi
    env_vars="$env_vars -e $var"
done

if [ "$(uname)" == "Darwin" ]; then
    docker_sock="/run/host-services/docker.proxy.sock"
else
    docker_sock="//var/run/docker.sock"
fi

echo "WARNING: This script is being deprecated and will be removed in a future release."
echo "         Please install uv (https://docs.astral.sh/uv/getting-started/installation)"
echo "         and then run 'uv tool install buildrunner' or 'uvx buildrunner' as documented"
echo "         here: https://github.com/adobe/buildrunner/blob/main/docs/installation.rst"
docker run \
        $env_vars \
        -v /$HOME:$HOME \
        --tty --interactive \
        -v $docker_sock:/var/run/docker.sock \
        -w /`pwd` \
        ghcr.io/adobe/buildrunner:latest $@
